# Generated by Django 2.2.24 on 2021-11-11 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mame',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 13, 36, 12, 485978, tzinfo=utc)),
        ),
    ]
